version: '3.8'
services:
  backend:
    container_name: back
    build: 
      context: api
    environment:
      - API_PORT=8088
    ports:
      - "8088:8088"
  frontend:
    depends_on:
      - backend
    container_name: front
    build: 
      context: front
    ports:
      - "8080:8080"

networks:
  default:
    name: app
